name: snap-license-example
base: core26
version: '0.2'
summary: &summary A demo snap for copying licenses
description: *summary
grade: devel
confinement: devmode

parts:
  license-root-file:  # project/LICENSE --> snap/LICENSE
    plugin: dump
    source: .
    stage:
      - LICENSE  # Pass along only the destination file

  license-fhs-file:  # project/LICENSE --> snap/usr/share/doc/foo/LICENSE
    plugin: dump
    source: .
    organize:
      "LICENSE": usr/share/doc/foo/
    stage:
      - usr/share/doc/foo/LICENSE  # Pass along only the destination file


  license-usr-dir:  # project/usr/share/doc/foo/* --> snap/usr/share/doc/foo/*
    plugin: dump
    source: ./usr/share/doc/foo/
